driver:
  name: vagrant
  network:
     - ["forwarded_port", {guest: 8080, host: 8080}]

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: centos-6.7
  - name: ubuntu-14.04

suites:
- name: default
  run_list:
  - recipe[zookeeper-service]
  - recipe[mesos::master]
  - recipe[mesos::slave]
  - recipe[marathon]
  - recipe[marathon::service]
  attributes:
    mesos:
      version: 0.25.0
    marathon:
      flags:
        master: zk://localhost:2181/mesos
    zookeeper:
      version: 3.4.8
      checksum: f10a0b51f45c4f64c1fe69ef713abf9eb9571bc7385a82da892e83bb6c965e90
