driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024
  network:
    # Allow access to the Jenkins webui which is useful when troubleshooting
    - - forwarded_port
      - guest: 8080
        host: 8080
        auto_correct: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.10.4
  data_path: test/shared

platforms:
- name: ubuntu-12.04
  run_list:
    - recipe[apt]
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

suites:
- name: default
  run_list:
    - recipe[zookeeper_apt]
    - recipe[marathon]
  attributes:
    marathon:
      options:
        http_port: 8080
