AllCops:
  Exclude:
    - vendor/**
    - bin/**

ClassAndModuleChildren:
  Enabled: false
ClassLength:
  Enabled: false
Documentation:
  Enabled: false
DoubleNegation:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
Next:
  Enabled: false
SpaceBeforeFirstArg:
  Enabled: false
TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
