### Disable line length constraint
Metrics/LineLength:
  Max: 120

ClassAndModuleChildren:
  Enabled: false
ClassLength:
  Enabled: false
Documentation:
  Enabled: false
DoubleNegation:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
Next:
  Enabled: false
SpaceBeforeFirstArg:
  Enabled: false
TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

### Align hashes as a table
Style/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
